import { commonFaqs } from './site'
export const supportingPages = {
  quality: {
    eyebrow:'Quality collaboration',title:'The evidence belongs with the work.',description:'Connect inspection results, technical context, and quality decisions to the relevant production record.',
    sections:[
      {eyebrow:'Inspection in context',title:'Read the result against the requirement.',paragraphs:['A measurement matters in relation to the part, revision, and inspection requirement. Velakron connects inspection results to that context so the people reviewing the work can understand what was recorded and what needs attention.','Inspection evidence supports the shared workflow. It does not mean Velakron manufactures, independently inspects, or certifies the physical part.'],media:'inspection'},
      {eyebrow:'A controlled response',title:'Keep a nonconformance and its disposition connected.',paragraphs:['When an inspection or quality concern needs follow-up, retain the affected production context and the appropriate formal record. The workflow can document containment, investigation, disposition, corrective action, evidence, and OEM verification.','Responsibility and the current state remain explicit. An issue, a production block, and a nonconformance are different workflows; an ordinary conversation is not a substitute for a required quality decision.'],media:'nonconformance'},
      {eyebrow:'A record you can return to',title:'Preserve what was decided—and where it applies.',paragraphs:['Keep a scoped approval with the affected production record. A decision accepted for a particular lot does not silently rewrite the released definition for every future order.','Shipment, physical receipt, inspection, and final acceptance remain distinct where the workflow requires them. Teams can return to the relevant evidence and history.'],media:'history'},
    ],faqs:[['Does Velakron provide quality certification?','No. Velakron provides software for inspection evidence and collaboration. Manufacturers, inspectors, and authorized reviewers remain responsible for their work and decisions.'],['Can we use this for controlled programs?','The current environment is not approved for classified information, ITAR or other export-controlled technical data, or CUI. Discuss the category of requirement before onboarding, without sending the material.']],
  },
  security: {
    eyebrow:'Security & data handling',title:'Shared work. Defined access.',description:'Understand how access is scoped in Velakron and the current limits on the data the environment can support.',
    sections:[
      {title:'Organization, relationship, and role',paragraphs:['Access to operational work is checked against the signed-in person’s organization, active membership, role, and relevant company relationship. A connection between an OEM and supplier does not make that work available to unrelated companies.','Administrators manage their own team’s access. Velakron platform support access is subject to authorization and audit controls; it is not an unrestricted public view of customer work.']},
      {title:'Private files and authorized access',paragraphs:['Part files and supporting attachments use private storage with authorization checks. Access to a record does not create a public file link. Temporary download links are issued through the application’s authorized workflows.','Account sessions and permissions are part of the product’s access controls. Protect your credentials, use an appropriately managed device, and remove access when people no longer need it.']},
      {title:'Confidentiality is part of participation',paragraphs:['Newly activated accounts accept versioned Platform Confidentiality Terms. Organizations retain the rights in their materials, and permitted use is tied to authorized work.','An OEM and supplier can also store an externally signed NDA for their relationship. That optional agreement adds its own terms; its presence or expiration is not the mechanism that grants platform access.'],link:['Read the Platform Confidentiality Terms','/confidentiality-terms']},
      {title:'The current data boundary',paragraphs:['The current environment is not approved for classified information, ITAR or other export-controlled technical data, or Controlled Unclassified Information (CUI). Do not upload or send those materials through the site, product, or application form.','An organization operating in aerospace or defense may have different categories of information. Selecting an industry or acknowledging a form notice does not approve data access. Discuss the requirement category with us before onboarding.'],link:['Acceptable use and current restrictions','/acceptable-use']},
      {title:'Evaluate the actual requirements',paragraphs:['If your procurement process requires a particular security certification, contractual control, data location, or assurance report, contact us before relying on the service for that use. This page does not claim SOC 2, ISO 27001, ITAR approval, or an independent certification.','File validation and private access do not amount to a guarantee that every upload has been malware scanned. The current prototype’s scanning limitations must be evaluated as part of onboarding.'],link:['Discuss your requirements','/contact']},
      {title:'Questions or suspected incidents',paragraphs:['Contact info@velakron.com to report a security concern or request the appropriate security contact. Describe the issue and how to reach you; do not email credentials, controlled technical files, or unnecessary confidential details.']},
    ],
  },
  faq: {
    eyebrow:'Frequently asked questions',title:'A clearer picture before you begin.',description:'Practical answers about Velakron, supplier participation, existing systems, and Early Access.',kind:'faq',
    faqs:[...commonFaqs,
      ['Does progress update automatically from machines?','No. The shared picture reflects information reported through the production workflow. Live machine telemetry is outside the current product scope.'],
      ['Is this a supplier marketplace?','The current product focuses on awarded production work and collaboration between participating companies. It is not an open marketplace that automatically matches new buyers and suppliers.'],
      ['Can our internal team use the same production context?','Authorized members can work from the information available to their organization and role. Engineering, operations, quality, and leadership can share context without giving every person the same permissions.'],
      ['What happens after I apply?','The team reviews the application and follows up about fit, data requirements, participating teams, and commercial scope. Selected partners then agree an offer and onboarding plan. Applying does not start billing.'],
      ['Can we see the product before applying?','Yes. The website includes actual product screens using synthetic data. You can also request a focused demo or use the visibility assessment to reflect on your current process.'],
      ['How are optional relationship NDAs handled?','The product can retain an externally signed NDA for an OEM–supplier relationship. The agreement’s dates do not automatically grant or remove product access. Account confidentiality terms and the product’s authorization controls remain separate.'],
    ],
  },
  contact: {
    eyebrow:'Contact Velakron',title:'Start with the work you want to improve.',description:'Talk with our team about production visibility, supplier participation, or the fit for your organization.',kind:'contact',
    sections:[{title:'A useful first conversation',paragraphs:['Tell us whether you are an OEM, a supplier, or both; how you currently coordinate production; and where the shared picture breaks down. You do not need to prepare a technical presentation.','Keep the first message about the workflow. Do not send drawings, credentials, controlled data, or confidential program details.']},{title:'Company',paragraphs:['Velakron LLC · Vancouver, Washington, USA. Our initial Early Access focus is North America.','Velakron’s current offering is software for shared production visibility and collaboration. A website inquiry does not request a manufacturing quote or place a production order.']}],
  },
  privacy: {
    eyebrow:'Privacy Notice',title:'How information from this website is used.',description:'Information about public website inquiries, Early Access applications, the visibility assessment, and your choices.',legal:true,
    sections:[
      {title:'Scope and contact',paragraphs:['This notice describes information handled by Velakron LLC through this website and its public inquiry, demonstration, and Early Access experiences. Contact info@velakron.com with privacy questions or a request concerning information you supplied.','The authenticated product also handles information on behalf of participating organizations. Their agreements and the applicable product terms govern the shared operational context. Do not submit personal or technical information that is unnecessary for your inquiry.']},
      {title:'Information you choose to provide',paragraphs:['An Early Access application collects your name, work email, company, participation role, location category, intended data category, and a general description of your coordination problem. It includes your contact permission and acknowledgment of the current data restrictions. Submitting the form sends this information to Velakron and creates an inquiry record; the page confirms receipt after the server accepts it.','A demo inquiry collects the contact and workflow information you submit. The visibility assessment processes your answers and requires business contact details and contact permission to display your score. Booking a demonstration is optional. Technical files are not requested by these forms.']},
      {title:'How we use it',paragraphs:['We use inquiry and application information to respond, evaluate the fit for the product or program, prepare a useful conversation, coordinate requested demonstrations, and maintain a record of the relationship. Submitted applications and subsequent correspondence become part of our inquiry records.','Information is available to the authorized Velakron team through its business systems. Contact permission for an application is used to respond about that application; this form does not enroll you in a newsletter.']},
      {title:'Service providers and disclosures',paragraphs:['Our hosting, database, business communication, and delivery providers process information needed to operate the site and respond to requests. Messages and replies pass through business communication services.','Information may also be disclosed where necessary to comply with applicable obligations, address security or misuse, or establish or protect rights. An Early Access application is not published as a customer testimonial or supplied as production data to another applicant.']},
      {title:'Browser storage and technical information',paragraphs:['The site and application use technical information needed to serve requests, maintain security, and diagnose failures. Server records may include request time, network address, browser information, and response status.','Early Access and demo form drafts use session storage in the current browser tab to recover after a refresh for up to 24 hours from the last change. Draft answers are sent to Velakron only when you submit. Drafts are cleared after confirmed receipt, when you select Clear answers, or when the browser ends the tab session. Contact permissions must be confirmed again after restoring a draft. The visibility assessment uses session storage to maintain its saved-result journey. Authentication uses session cookies when you sign in. The public revamp does not add advertising trackers or a newsletter signup.']},
      {title:'Retention and your choices',paragraphs:['We retain submitted information as needed to manage the inquiry or relationship and meet applicable recordkeeping, security, or legal requirements. Different operational records can have different retention needs; submitting the form does not set an automatic deletion date.','You may ask to correct information, discuss access or deletion, or stop further application follow-up by contacting info@velakron.com. We may need to verify the request and consider records that must be retained. Use Clear answers to remove the local form draft, particularly on a shared device. A message you choose to send separately by email is also managed by your email service.']},
      {title:'Data we do not request',paragraphs:['These public forms are for business inquiries. Do not include passwords, payment-card details, government identifiers, unnecessary sensitive personal information, classified material, ITAR or other export-controlled technical data, or CUI.','If your intended workflow has special handling requirements, describe the category of requirement without sending the underlying material.']},
      {title:'Changes to this notice',paragraphs:['We may update this notice as the website or handling practices change. The date below identifies this version. Questions about a prior submission can be sent to the contact address above.']},
    ],
  },
  terms: {
    eyebrow:'Website terms',title:'Using the Velakron website.',description:'The scope of public website information, inquiries, and Early Access applications.',legal:true,
    sections:[
      {title:'Public information and inquiries',paragraphs:['This website introduces Velakron LLC and its production visibility and collaboration software. Public information and illustrative product screens help you evaluate a conversation with us. Synthetic companies and production data are examples, not customer references.','Use the website lawfully and provide accurate information you are authorized to share. Do not interfere with its operation, attempt unauthorized access, impersonate another person, or submit malicious content.']},
      {title:'Early Access and commercial scope',paragraphs:['Submitting an application is an expression of interest. It does not accept your organization into Early Access, create an account, purchase a subscription, authorize an upload, or guarantee product features or availability.','Participation, fees, discounts, duration, support scope, and any other commercial commitments are established in the applicable offer or agreement. Website descriptions do not change an existing signed agreement or billing arrangement.']},
      {title:'Product and confidentiality terms',paragraphs:['Authenticated product use is subject to the applicable account and service terms, including the versioned Platform Confidentiality Terms accepted during account activation. Those terms remain separate from a public inquiry.','Each organization retains its rights in its materials. Only share material for which you have the necessary authority. An optional OEM–supplier NDA is a separate agreement between its parties.'],link:['Read the Platform Confidentiality Terms','/confidentiality-terms']},
      {title:'Current capabilities and examples',paragraphs:['Product capabilities, configuration, and availability can change. An illustrative screenshot shows a particular workflow state using sample data. It does not guarantee the outcome of an actual manufacturing process.','Velakron provides software. OEMs, suppliers, and authorized reviewers remain responsible for production, inspection, engineering, delivery, and acceptance decisions. Roadmap discussion and partner feedback do not themselves create a commitment to implement a feature.']},
      {title:'Data restrictions',paragraphs:['The current environment is not approved for classified information, ITAR or other export-controlled technical data, or CUI. Do not send such material through the website, email inquiry, or application. A form acknowledgment is not approval to handle it.'],link:['Read acceptable use and data restrictions','/acceptable-use']},
      {title:'Questions',paragraphs:['Contact info@velakron.com about the website, an application, or the terms that apply to your organization. For information about handling public inquiry data, see the Privacy Notice.'],link:['Privacy Notice','/privacy']},
    ],
  },
  'acceptable-use': {
    eyebrow:'Acceptable use & data restrictions',title:'Start with data the environment can support.',description:'Current restrictions for public inquiries, Early Access qualification, and product use.',legal:true,
    sections:[
      {title:'Current controlled-data boundary',paragraphs:['The current environment is not approved for classified information, ITAR or other export-controlled technical data, Controlled Unclassified Information (CUI), or other regulated data requiring special handling. Do not upload, paste, attach, or send these materials through the website, application, or ordinary inquiry email.','A technical capability, an industry label, an Early Access application, or an acknowledgment checkbox does not authorize that data. Describe only the category of requirement during qualification so we can discuss whether an appropriate future arrangement is possible.']},
      {title:'Share only what is needed and authorized',paragraphs:['For a public inquiry, provide business contact information and a general description of the coordination problem. Do not include detailed drawings, private customer or program information, credentials, payment information, or unnecessary personal data.','Within an authorized product workspace, share only material you have the right to provide for the relevant work. Follow organization, relationship, role, and confidentiality requirements. Access to one organization’s work is not permission to reuse it for another.']},
      {title:'Protect the workspace',paragraphs:['Do not share account credentials, bypass access controls, attempt to retrieve another organization’s private records, or make private materials publicly available. Do not submit malware, malicious scripts, deceptive requests, or content intended to disrupt the service.','Use the product’s supported workflows for updates and decisions. Do not falsify inspection evidence, impersonate an approver, or obscure a required production or quality action.']},
      {title:'If you are unsure',paragraphs:['Stop before sending the material. Contact info@velakron.com with the category of requirement and a way to reach you. Do not include the underlying technical data in that message.','If information was shared in error or you suspect unauthorized access, report the concern promptly so the team can assess the appropriate response.']},
      {title:'Related information',paragraphs:['The security page describes implemented access controls and current limitations. The Platform Confidentiality Terms set out the confidentiality duties accepted at account activation.'],link:['Security and data handling','/security']},
    ],
  },
}
