import Seo from '../components/marketing/MarketingSeo'
import { supportingPages } from '../content/marketing/supportingPages'
import { withMarketing } from '../components/marketing/MarketingLayout'
import { PageHero, FeatureStory, FaqList, TextLink, FinalCta, CtaLink, Contents, PolicyText, sectionId } from '../components/marketing/Elements'
import ProductFigure from '../components/marketing/ProductFigure'
const policyLinks = [['Privacy Notice','/privacy'],['Website terms','/terms'],['Acceptable use','/acceptable-use'],['Confidentiality terms','/confidentiality-terms']]
function InformationPage({page,slug}) { const editorial = page.legal || slug==='security'; return <>
  <Seo title={page.eyebrow} description={page.description} path={`/${slug}`} />
  <PageHero compact eyebrow={page.eyebrow} title={page.title} action={slug==='quality'}><p>{page.description}</p>{page.legal && <p className='mk-policy-date'>Version: September 10, 2026 · Velakron</p>}</PageHero>
  {slug==='security' && <section className='mk-section mk-tint'><div className='mk-container'><div className='mk-summary-grid'><article className='mk-summary-card'><h2>Scoped access</h2><p>Organization, relationship, and role determine access to shared work.</p><a className='mk-text-link' href='#organization-relationship-and-role'>How access works</a></article><article className='mk-summary-card'><h2>Current data limits</h2><p>No classified information, ITAR/export-controlled technical data, or CUI in the current environment.</p><TextLink href='/acceptable-use'>Data restrictions</TextLink></article><article className='mk-summary-card'><h2>Security questions</h2><p>Discuss procurement requirements or report a concern before sharing technical material.</p><a className='mk-text-link' href='mailto:info@velakron.com'>info@velakron.com</a></article></div></div></section>}
  {page.kind==='contact' && <section className='mk-section mk-tint'><div className='mk-container mk-contact-options'><article><h2>See the product</h2><p>Arrange a focused conversation around your team’s needs.</p><CtaLink href='/request-demo'>Request a demo</CtaLink></article><article><h2>Join Early Access</h2><p>Bring a production workflow to the partner program.</p><CtaLink secondary /></article><article><h2>Ask a question</h2><p>For company, supplier, data, or other inquiries.</p><a className='mk-text-link' href='mailto:info@velakron.com'>info@velakron.com</a></article></div></section>}
  {slug==='quality' ? page.sections.map((section,index) => <FeatureStory key={section.title} id={sectionId(section.title)} number={`0${index+1}`} eyebrow={section.eyebrow} title={section.title} reverse={index%2===0} media={<ProductFigure name={section.media} />}>{section.paragraphs.map(text => <p key={text}>{text}</p>)}</FeatureStory>) : page.sections && <section className='mk-section'><div className={`mk-container${editorial ? ' mk-policy-layout' : ''}`}>
    {editorial && <Contents items={page.sections.map(section => ({id:sectionId(section.title),title:section.title}))} label='On this page' />}
    <article className='mk-editorial'>{page.sections.map(section => <section key={section.title} id={sectionId(section.title)}><h2>{section.title}</h2>{section.paragraphs.map(text => <p key={text}><PolicyText text={text} /></p>)}{section.link && <TextLink href={section.link[1]}>{section.link[0]}</TextLink>}</section>)}{page.legal && <nav className='mk-article-links' aria-label='Related policies'>{policyLinks.filter(([,href]) => href!==`/${slug}`).map(([label,href]) => <TextLink href={href} key={href}>{label}</TextLink>)}<button className='mk-text-button' type='button' onClick={() => window.print()}>Print / save as PDF</button></nav>}</article>
  </div></section>}
  {page.faqs && <section className='mk-section'><div className='mk-container mk-narrow'>{page.kind==='faq' ? <><nav className='mk-step-nav' aria-label='FAQ topics'><a href='#product-workflow'>Product & workflow</a><a href='#participation-pricing'>Participation & pricing</a><a href='#data-access'>Data & access</a></nav>{[['Product & workflow',[0,1,6,7,10]],['Participation & pricing',[2,3,5,9]],['Data & access',[4,8,11]]].map(([title,indices]) => <section className='mk-faq-group' key={title} id={sectionId(title)}><h2>{title}</h2><FaqList items={indices.map(index => {const item=page.faqs[index];const destination=index===4?['Data restrictions','/acceptable-use']:index===11?['Confidentiality terms','/confidentiality-terms']:index===8?['Access and security','/security']:index===10?['Request a demo','/request-demo']:[2,3,5,9].includes(index)?['Explore Early Access','/early-access']:['Explore the workflow','/how-it-works'];return [...item.slice(0,2),[destination]]})} /></section>)}</> : <FaqList items={page.faqs} />}</div></section>}
  {!page.legal && page.kind!=='contact' && <FinalCta />}
</> }
export const getStaticPaths = () => ({paths:Object.keys(supportingPages).map(slug=>({params:{slug}})),fallback:false})
export const getStaticProps = ({params}) => ({props:{page:supportingPages[params.slug],slug:params.slug}})
export default withMarketing(InformationPage)
