import Seo from '../components/marketing/MarketingSeo'
import { withMarketing } from '../components/marketing/MarketingLayout'
import { PageHero, SectionHeading, TextLink, FinalCta } from '../components/marketing/Elements'
import ProductFigure from '../components/marketing/ProductFigure'

function About() { return <>
  <Seo title='About Velakron' path='/about' description='Why Velakron is building shared production visibility and collaboration software for OEMs and manufacturing suppliers.' />
  <PageHero eyebrow='About Velakron' title='Good manufacturing depends on shared understanding.'><p>We’re building software for the information gap between the company relying on a part and the supplier making it.</p></PageHero>
  <section className='mk-section'><div className='mk-container mk-split'><SectionHeading eyebrow='The problem behind the product' title='Too much important context lives between systems.' /><div><p>Outsourced manufacturing brings capable teams together. It also puts production status, technical questions, and decisions across company boundaries. A clear internal plan does not automatically create a shared external picture.</p><p>When that picture is fragmented, people compensate: more calls, more spreadsheets, more meetings, and more time finding the person who knows. Velakron gives that shared work a place to live.</p><p>Velakron LLC is building a Manufacturing Intelligence Platform, beginning with production visibility and collaboration for awarded work. Our current Early Access focus is practical: a useful production record, relevant part context, clear responsibility, and retained evidence.</p></div></div></section>
  <section className='mk-section mk-tint'><div className='mk-container'><SectionHeading eyebrow='Our starting point' title='Make the next manufacturing decision easier.'>A person opening a record should be able to understand what is happening, who needs to act, and what information supports the decision.</SectionHeading><ProductFigure name='conversation' /></div></section>
  <section className='mk-section'><div className='mk-container'><SectionHeading eyebrow='Manufacturing experience, software focus' title='Built around the people doing the work.' /><div className='mk-audiences'><article><p className='mk-label'>Engineering & manufacturing</p><h3>Keve Shoemaker</h3><p>Keve’s background includes more than 20 years in manufacturing and automation. That experience grounds the product in the practical details of part definitions, production commitments, and communication between teams.</p></article><article><p className='mk-label'>Business operations & customer experience</p><h3>Jenny Shoemaker</h3><p>Jenny brings the operations and customer-experience perspective: how teams adopt a process, communicate clearly, and maintain an accountable working relationship.</p></article></div><p className='mk-workflow-note'>Based in Vancouver, Washington. Our initial partner focus is North America.</p></div></section>
  <section className='mk-section mk-tint'><div className='mk-container mk-split'><SectionHeading eyebrow='Where we are today' title='Early Access, with a real product to work in.'>We are inviting a limited group of OEMs and suppliers to use the shared workflow through a complete production cycle.</SectionHeading><div><p>Selected partners help us understand real adoption, the quality of shared updates, and the decisions teams need to make. We provide guided onboarding and direct support within an agreed scope.</p><p>Our focus is software for shared production work. Applying does not request a manufacturing quote, join an open supplier marketplace, or create a subscription.</p><TextLink href='/early-access'>Explore the partner program</TextLink><div className='mk-rule' /><TextLink href='/contact'>Talk with the Velakron team</TextLink></div></div></section>
  <FinalCta title='Help shape a clearer way to work together.' />
</> }
export default withMarketing(About)
