import Seo from '../components/marketing/MarketingSeo'
import { withMarketing } from '../components/marketing/MarketingLayout'
import { PageHero, SectionHeading, TextLink, FinalCta } from '../components/marketing/Elements'

function About() { return <>
  <Seo title='About Velakron' path='/about' description='Meet the manufacturing, operations, and software backgrounds behind Velakron’s shared production workspace.' />
  <PageHero eyebrow='About Velakron' title='Manufacturing experience. Software focus.' action={false} compact><p>We’re building software for the information gap between the company relying on a part and the supplier making it.</p></PageHero>
  <section className='mk-section'><div className='mk-container'><div className='mk-team-origin'><SectionHeading eyebrow='Why we started' title='Too much time goes into finding the current answer.' /><p>Outsourced production puts dates, technical questions, and decisions across company boundaries. Velakron gives both teams a place to maintain the production record and understand what needs to happen next.</p></div><div className='mk-audiences mk-audiences--team'>
    <article><p className='mk-label'>Engineering & manufacturing</p><h3>Keve Shoemaker</h3><p>Keve brings more than 20 years in manufacturing and automation. His experience grounds the product in part definitions, production commitments, and the practical communication between teams.</p></article>
    <article><p className='mk-label'>Business operations & customer experience</p><h3>Jenny Shoemaker</h3><p>Jenny brings the operations and customer-experience perspective: how teams adopt a process, communicate clearly, and maintain an accountable working relationship.</p></article>
    <article><p className='mk-label'>Software & technology</p><h3>Pedro Lara</h3><p>Pedro brings a background in software and technology. He focuses on turning complex requirements into practical digital tools and shaping the workflows that connect manufacturing teams.</p></article>
  </div><div className='mk-proof-strip'><span>Velakron LLC</span><span>Vancouver, Washington, USA</span><span>Initial partner focus: North America</span></div></div></section>
  <section className='mk-section mk-tint'><div className='mk-container mk-split'><SectionHeading eyebrow='Where we are today' title='An actual product. A focused Early Access program.'>We’re working with selected OEMs and suppliers through a complete production cycle.</SectionHeading><div><p>Partners bring suitable work, participating people, and candid feedback. We provide guided onboarding, direct support, and an agreed commercial scope.</p><p>Our starting point is shared production visibility: awarded work, part context, supplier updates, conversations, and retained evidence.</p><div className='mk-actions'><TextLink href='/how-it-works'>Explore the workflow</TextLink><TextLink href='/early-access'>The partner program</TextLink></div></div></div></section>
  <FinalCta title='Talk with the people building Velakron.' href='/contact' action='Contact the team'>Bring the coordination problem you want to solve. We’ll discuss whether the current product and Early Access scope fit.</FinalCta>
</> }
export default withMarketing(About)
