import Seo from '../components/marketing/MarketingSeo'
import { withMarketing } from '../components/marketing/MarketingLayout'
import { PageHero, FeatureStory, SectionHeading, CheckList, TextLink, FaqList, FinalCta } from '../components/marketing/Elements'
import ProductFigure from '../components/marketing/ProductFigure'
import { commonFaqs } from '../content/marketing/site'

function ForOems() { return <>
  <Seo title='Production visibility for OEMs' path='/for-oems' description='Understand supplier progress, production commitments, technical questions, and quality evidence in a shared OEM–supplier workspace.' />
  <PageHero eyebrow='For OEMs' title='Know where your outsourced work stands.' aside={<ProductFigure name='worklist' priority />}><p>Bring supplier progress, dates, and decisions into a production picture your whole team can understand. Spend less time reconstructing the answer.</p></PageHero>
  <section className='mk-section'><div className='mk-container mk-split'><SectionHeading eyebrow='The information between companies' title='A production plan needs a current production picture.'>Your internal plan may be clear. What is happening at a supplier can still be scattered across emails, calls, spreadsheets, and individual relationships.</SectionHeading><div><p>Procurement needs a commitment. Engineering needs the right revision. Quality needs evidence. Leadership needs to understand the risk. Those questions should start from the same record.</p><CheckList items={['Which supplier has accepted the work?','What stage is it in, and when was it updated?','What date is committed, and what arrival is required?','Who needs to respond before the work can move forward?']} /></div></div></section>
  <FeatureStory number='01' eyebrow='The commitment in context' title='The part. The supplier. The dates.' media={<ProductFigure name='record' />} reverse><p>Every awarded production record holds its own part and revision context, quantity, supplier, stage, required arrival, and expected ship date.</p><p>Read the latest update alongside the commitment. A current stage tells you where the work is; schedule health and attention reasons explain what needs a closer look.</p><CheckList items={['Required arrival and expected ship stay distinct','Update freshness remains visible','History stays with the production record']} /></FeatureStory>
  <FeatureStory number='02' eyebrow='Exceptions with ownership' title='Know what needs a decision—and whose.' media={<ProductFigure name='issue' />}><p>A manufacturing question, a formal issue, and stopped production need different responses. Velakron keeps the relevant state, next responsible company, and decision history explicit.</p><p>Work from a documented proposed resolution. Preserve the scope of an approval, including when it applies to one production lot. A production block remains a controlled workflow through release and resumption.</p><TextLink href='/how-it-works'>Follow the shared workflow</TextLink></FeatureStory>
  <FeatureStory number='03' eyebrow='Engineering and quality, connected' title='Put the question beside the part.' media={<ProductFigure name='conversation' />} reverse><p>Discuss the applicable drawing or model revision with the manufacturing context close at hand. Keep the clarification with the work instead of relying on a forwarded email chain.</p><p>Inspection results and related quality review also belong to the production story. Authorized teams can understand the evidence and the follow-up it requires.</p><TextLink href='/quality'>Explore quality collaboration</TextLink></FeatureStory>
  <section className='mk-section'><div className='mk-container mk-split'><SectionHeading eyebrow='Adoption is part of the work' title='Start with a supplier group you can work with.'>Shared visibility depends on participation. Start with a practical scope, named owners, and an update rhythm both sides can maintain.</SectionHeading><div className='mk-tool-fit'><div><span className='mk-label'>Your team</span><h3>Bring the commitment and the context.</h3><p>Choose suitable production work, connect participating suppliers, and make sure the relevant part definition and dates are clear.</p></div><div><span className='mk-label'>Your suppliers</span><h3>Keep the shared picture current.</h3><p>Accept work, report meaningful progress, and raise concerns while there is still a useful decision to make. Supplier participation is supported within the OEM plan.</p></div><div><span className='mk-label'>Our team</span><h3>Help the workflow take hold.</h3><p>During Early Access, we work with selected partners on onboarding, a complete production cycle, and practical feedback. Your internal ERP or planning system can remain in place.</p></div><TextLink href='/for-suppliers'>See the supplier’s side</TextLink></div></div></section>
  <section className='mk-section mk-tint'><div className='mk-container mk-narrow'><SectionHeading eyebrow='Before you begin' title='A few practical questions.' /><FaqList items={commonFaqs.filter((_,i) => [1,2,3,4].includes(i))} /></div></section>
  <FinalCta title='A clearer view starts with a shared commitment.'>Apply with a production workflow your team wants to improve. We’ll discuss fit, participating suppliers, and a practical Early Access scope.</FinalCta>
</> }
export default withMarketing(ForOems)
