import { MessageSquare, Clock3, CircleAlert, Building2, Factory, ShieldCheck } from 'lucide-react'
import Seo from '../components/marketing/MarketingSeo'
import { withMarketing } from '../components/marketing/MarketingLayout'
import { CtaLink, TextLink, SectionHeading, CheckList, FinalCta } from '../components/marketing/Elements'
import ProductFigure from '../components/marketing/ProductFigure'
import ProductGallery from '../components/marketing/ProductGallery'

function Home() { return <>
  <Seo title='Production visibility. Shared.' path='/' description='Track outsourced production, share supplier updates, and resolve part questions in one workspace for OEMs and manufacturing suppliers.' />
  <section className='mk-hero mk-grid-bg'><div className='mk-container mk-hero__inner'>
    <div className='mk-hero__copy'><p className='mk-eyebrow'>Production visibility. Shared.</p><h1>Stop asking.<br /><em>Start knowing.</em></h1><p className='mk-hero__lead'>Track outsourced production, share supplier updates, and resolve part questions in one workspace. Know what changed and who needs to act next.</p><div className='mk-cohort'><span />Now welcoming Early Access partners</div><div className='mk-actions'><CtaLink /><CtaLink href='/how-it-works' secondary>See how it works</CtaLink></div><div className='mk-hero__facts'><span>OEM + supplier views</span><span>Part-specific conversations</span><span>Retained production history</span></div></div>
    <div className='mk-hero__media'><ProductFigure name='overview' priority placement='hero' caption='Start with the production records that need a response.' /></div>
  </div></section>
  <section className='mk-section'><div className='mk-container'><SectionHeading eyebrow='The everyday coordination problem' title='The update exists. Finding it takes another call.' /><div className='mk-problems mk-problems--three'>
    <article><MessageSquare aria-hidden /><h3>Repeated status requests.</h3><p>The supplier already sent an update. Purchasing, engineering, and operations still ask separately.</p></article>
    <article><Clock3 aria-hidden /><h3>Dates without context.</h3><p>A changed ship date sits in an inbox, apart from the required arrival and production stage.</p></article>
    <article><CircleAlert aria-hidden /><h3>A decision waiting unnoticed.</h3><p>A drawing question or quality concern needs an answer before the next operation can begin.</p></article>
  </div></div></section>
  <section className='mk-section mk-tint' id='product'><div className='mk-container'><SectionHeading eyebrow='See the product' title='Find the change. Take the next step.'>Actual product examples, focused on the decisions teams make.</SectionHeading><ProductGallery /></div></section>
  <section className='mk-section' id='teams'><div className='mk-container'><SectionHeading eyebrow='Two sides of the same work' title='Useful for the buyer. Practical for the supplier.' /><div className='mk-audiences'>
    <article><Building2 size={28} aria-hidden /><p className='mk-label'>For OEMs</p><h3>Know where each order stands.</h3><p>For companies coordinating outsourced manufacturing: see supplier progress, changed dates, and the questions your team needs to answer.</p><TextLink href='/for-oems'>Explore the OEM view</TextLink></article>
    <article><Factory size={28} aria-hidden /><p className='mk-label'>For suppliers</p><h3>Give the update once.</h3><p>Keep connected customers informed, ask for the clarification you need, and retain the answer with the part.</p><TextLink href='/for-suppliers'>Explore the supplier view</TextLink></article>
  </div><p className='mk-scope-note'>Keep internal planning in your ERP or MRP. Teams maintain the shared production record in Velakron; direct ERP synchronization is outside the current Early Access scope.</p></div></section>
  <section className='mk-section mk-access' id='early-access'><div className='mk-container mk-split'><div><p className='mk-eyebrow'>Early Access</p><h2>A real production cycle.<br />Support from our team.</h2><p>We’re working with a limited group of OEMs and suppliers in North America, coordinating complex parts over weeks or months.</p><TextLink href='/early-access'>Explore the partner program</TextLink></div><div className='mk-exchange'><h3>Start with a manageable group.</h3><CheckList items={['Suitable production work and participating people','Guided onboarding and direct support','Paid participation under an agreed discounted offer']} /><p className='mk-fine'>We discuss fit, data requirements, pricing, and the participation period before enrollment. Applying does not start billing.</p></div></div></section>
  <section className='mk-section'><div className='mk-container mk-trust'><div><ShieldCheck size={28} aria-hidden /><p className='mk-eyebrow'>The people behind Velakron</p><h2>Manufacturing experience.<br />Software focus.</h2><p>Our team brings engineering, manufacturing, operations, and technology backgrounds to the coordination problem.</p><TextLink href='/about'>Meet the team</TextLink></div><div><h3>Share with the right people.</h3><p>Access follows your organization, connected relationships, and role. Begin with suitable non-controlled data.</p><TextLink href='/security'>Security and current data limits</TextLink><div className='mk-rule' /><h3>Where does your process lose visibility?</h3><p>Eight questions to reflect on status, follow-up, and delay awareness. Work contact details are required to view your score.</p><TextLink href='/visibility-assessment'>Take the visibility assessment</TextLink></div></div></section>
  <FinalCta />
</> }
export default withMarketing(Home)
