import Seo from '../../components/marketing/MarketingSeo'
import { withMarketing } from '../../components/marketing/MarketingLayout'
import { PageHero, SectionHeading, CheckList, TextLink, FaqList } from '../../components/marketing/Elements'
import EarlyAccessForm from '../../components/marketing/EarlyAccessForm'
import { commonFaqs } from '../../content/marketing/site'
function EarlyAccess() { return <>
  <Seo title='Apply for Early Access' path='/early-access' description='Join a limited group of OEMs and manufacturing suppliers using Velakron through a real production cycle. Explore the program and apply.' />
  <PageHero compact eyebrow='Early Access · limited partner cohort' title='Bring a real workflow. Help build a better one.' action={false}><p>We’re inviting OEMs and suppliers to use Velakron through a complete production cycle—with guided onboarding, direct support, and room for candid feedback.</p><a className='mk-button' href='#application' onClick={() => requestAnimationFrame(() => document.getElementById('ea-full_name')?.focus({preventScroll:true}))}>Start your application</a></PageHero>
  <section className='mk-section mk-inquiry-section'><div className='mk-container mk-application-layout'><aside><SectionHeading eyebrow='Your application' title='Start with the coordination problem.'>No technical files are needed. Share enough for us to understand your organization and the workflow you want to improve.</SectionHeading><p>This is a paid partner program with an agreed discounted offer. Submit your application here; the page will confirm receipt.</p><ol className='mk-application-steps'><li><strong>Apply</strong><span>Tell us about the participants and the work.</span></li><li><strong>Discuss fit and scope</strong><span>We review your application and follow up about suitability, data requirements, and an offer.</span></li><li><strong>Onboard selected partners</strong><span>Agree participation, introduce the people involved, and begin a useful production cycle.</span></li></ol><p className='mk-scope-note'>Applying does not start billing or guarantee enrollment. Feedback informs priorities; it does not guarantee custom features.</p><TextLink href='/request-demo'>See the product first</TextLink></aside><EarlyAccessForm /></div></section>
  <section className='mk-section'><div className='mk-container mk-split'><SectionHeading eyebrow='Who this is for' title='Teams with meaningful work between companies.'>Our initial focus is North America, with complex outsourced parts and production cycles measured in weeks or months.</SectionHeading><div><CheckList items={['An OEM coordinating work with external manufacturing suppliers','A supplier keeping OEM customers informed about production','People on both sides willing to participate and keep updates current','Suitable non-controlled production data and a complete cycle to learn from']} /><p>Space, aerospace, robotics, industrial equipment, and other precision manufacturing teams can have this coordination problem. Sector alone does not determine data suitability. Companies outside our initial profile can still discuss fit.</p></div></div></section>
  <section className='mk-section mk-tint'><div className='mk-container'><SectionHeading eyebrow='A clear exchange' title='A working partnership, with an agreed scope.' /><div className='mk-audiences'><article><p className='mk-label'>Your contribution</p><h3>Real participation.</h3><CheckList items={['Suitable production work and participating counterparts','Named people to maintain the shared workflow','Use through a complete production cycle','Specific feedback on the work and the experience','Paid participation under an agreed offer']} /></article><article><p className='mk-label'>Our contribution</p><h3>Support from the start.</h3><CheckList items={['Guided setup and onboarding','Direct support from the Velakron team','An agreed discounted Early Access offer','A structured way to share feedback','Input into product priorities as we learn']} /></article></div><p className='mk-workflow-note'>Pricing and the participation period are discussed after qualification. Feedback informs priorities; it does not guarantee bespoke features. Applying is not enrollment and does not start billing.</p></div></section>
  <section className='mk-section mk-tint'><div className='mk-container mk-narrow'><SectionHeading eyebrow='Before applying' title='What to expect.' /><FaqList items={commonFaqs.filter((_,i) => [2,3,4,5].includes(i))} /></div></section>
</> }
export default withMarketing(EarlyAccess)
