import Seo from '../../components/marketing/MarketingSeo'
import { withMarketing } from '../../components/marketing/MarketingLayout'
import { PageHero, SectionHeading, CheckList, TextLink, FaqList } from '../../components/marketing/Elements'
import EarlyAccessForm from '../../components/marketing/EarlyAccessForm'
import { commonFaqs } from '../../content/marketing/site'
function EarlyAccess() { return <>
  <Seo title='Apply for Early Access' path='/early-access' description='Apply to use Velakron through a real production cycle with guided onboarding and direct support.' />
  <PageHero compact eyebrow='Early Access · limited partner cohort' title='Bring a real production workflow.' action={false}><p>Join a paid partner program with guided onboarding, direct support, and an agreed discounted offer. Our initial focus is OEMs and suppliers in North America.</p><a className='mk-button' href='#application' onClick={() => requestAnimationFrame(() => document.getElementById('ea-full_name')?.focus({preventScroll:true}))}>Start your application</a></PageHero>
  <section className='mk-section mk-inquiry-section'><div className='mk-container mk-application-layout'><aside><SectionHeading eyebrow='A working partnership' title='One useful production cycle.'>Start with suitable non-controlled work, participating people on both sides, and a shared problem worth solving.</SectionHeading><CheckList items={['Use the workflow through a complete production cycle','Keep updates current and share specific feedback','Agree scope, pricing, and the participation period before onboarding']} /><h3>What you receive</h3><p>Guided setup, direct support, and a structured way to influence product priorities.</p><ol className='mk-application-steps'><li><strong>Apply</strong><span>Introduce your team and coordination problem.</span></li><li><strong>Discuss fit</strong><span>Review participants, data requirements, and the offer.</span></li><li><strong>Begin together</strong><span>Selected partners agree a plan and start onboarding.</span></li></ol><p className='mk-scope-note'>Applying does not start billing or guarantee enrollment. Feedback informs priorities; it does not guarantee custom features.</p><TextLink href='/request-demo'>See the product first</TextLink></aside><EarlyAccessForm /></div></section>
  <section className='mk-section mk-tint'><div className='mk-container mk-narrow'><SectionHeading eyebrow='Before applying' title='What to expect.' /><FaqList items={commonFaqs.filter((_,i) => [2,3,4,5].includes(i))} /></div></section>
</> }
export default withMarketing(EarlyAccess)
